<a href="https://colab.research.google.com/github/rosefromtheashes/Machine-Learning-Bootcamp/blob/main/template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello Colab')

Hello Colab


### Import bibliotek


In [1]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.2.2'

### Wygenerowanie danych

In [2]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

### Utworzenie kopii danych

In [3]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


### Zmiana typu danych i wstępna eksploracja


In [4]:
for col in ['size', 'color', 'gender', 'bought']:
    df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 740.0 bytes


In [5]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

#Aby dodać zmienne katergoryczne, musimy dodać (include=['category'])


In [7]:
df.describe(include=['category']).T

count unique     top freq
size       5      3       L    2
color      5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df['bought'])
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [9]:
le.fit_transform(df['bought'])

array([1, 0, 1, 0, 1])

In [10]:
le.classes_

array(['no', 'yes'], dtype=object)

In [12]:
df['bought'] = le.fit_transform(df['bought'])
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

### OneHotEncoder

In [15]:
from sklearn.preprocessing import OneHotEncoder

encoder= OneHotEncoder(sparse = False)
encoder.fit(df[['size']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


OneHotEncoder(sparse=False, sparse_output=False)

In [16]:
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [17]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [19]:
encoder = OneHotEncoder(drop = 'first', sparse = False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

Pandas *get_dummies()*

In [20]:
pd.get_dummies(data=df)

price  weight  bought  size_L  size_M  size_XL  color_blue  color_green  \
0  199.0   500.0       1       0       0        1           0            0   
1   89.0   450.0       0       1       0        0           0            1   
2   99.0   300.0       1       0       1        0           1            0   
3  129.0   380.0       0       1       0        0           0            1   
4   79.0   410.0       1       0       1        0           0            0   

   color_red  gender_female  gender_male  
0          1              1            0  
1          0              0            1  
2          0              0            1  
3          0              1            0  
4          1              1            0

In [21]:
pd.get_dummies(data=df, drop_first=True)

price  weight  bought  size_M  size_XL  color_green  color_red  gender_male
0  199.0   500.0       1       0        1            0          1            0
1   89.0   450.0       0       0        0            1          0            1
2   99.0   300.0       1       1        0            0          0            1
3  129.0   380.0       0       0        0            1          0            0
4   79.0   410.0       1       1        0            0          1            0

In [23]:
#żeby zakodować tylko jedną kolumnę, możemy to zrobić następującym sposobem:
pd.get_dummies(data=df, drop_first=True, columns=['size'])

color  gender  price  weight  bought  size_M  size_XL
0    red  female  199.0   500.0       1       0        1
1  green    male   89.0   450.0       0       0        0
2   blue    male   99.0   300.0       1       1        0
3  green  female  129.0   380.0       0       0        0
4    red  female   79.0   410.0       1       1        0